CREATE TABLE IF NOT EXISTS case_studies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  client VARCHAR(255) NOT NULL,
  client_role VARCHAR(255) NULL,
  category VARCHAR(120) NOT NULL,
  excerpt TEXT NOT NULL,
  challenge LONGTEXT NOT NULL,
  solution LONGTEXT NOT NULL,
  results_json LONGTEXT NOT NULL,
  technologies_json TEXT NOT NULL,
  cover_image TEXT NULL,
  cover_image_alt VARCHAR(255) NULL,
  client_quote TEXT NULL,
  client_image TEXT NULL,
  related_slugs_json TEXT NULL,
  published TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_case_studies_slug (slug),
  KEY idx_case_studies_published (published),
  KEY idx_case_studies_category (category),
  KEY idx_case_studies_sort_order (sort_order)
);

INSERT INTO case_studies (
  slug,
  title,
  client,
  client_role,
  category,
  excerpt,
  challenge,
  solution,
  results_json,
  technologies_json,
  cover_image,
  cover_image_alt,
  client_quote,
  client_image,
  related_slugs_json,
  published,
  sort_order
)
VALUES
  (
    'ai-logistics-transformation',
    'AI-Powered Logistics Transformation',
    'GlobalFreight Solutions',
    'Executive Sponsor',
    'AI Automation',
    'How we automated route optimization and reduced delivery costs by 35% using custom AI agents.',
    'GlobalFreight was spending 40+ hours per week on manual route planning across 200+ delivery vehicles. Their legacy system couldn''t handle real-time traffic data or dynamic customer priorities.',
    'We built a custom AI-powered route optimization engine that processes real-time traffic, weather, and priority data. The system auto-assigns deliveries, optimizes routes every 15 minutes, and provides a live dashboard for fleet managers.',
    '[{"metric":"35%","label":"Cost Reduction"},{"metric":"40hrs","label":"Weekly Hours Saved"},{"metric":"98.5%","label":"On-Time Delivery"},{"metric":"2.5x","label":"Fleet Efficiency"}]',
    '["Python","TensorFlow","Next.js","PostgreSQL","Redis"]',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAFlvMBUpYvpWH3dHiMdarFZN3MlWoXyk50_XR9iZM0oziHKYZdc32GWiy6bX1JsPlNxmWFl9ilfRbcCKVhKFzCnpYcmm9NKsepk7D-D1lQB_wGoK7SYnzd9yF-3eA3BQPfz5_lQlOFlLy7h71GOmjglJG4iQJtvl8yH_TOMVrffOhU-gOzuy44mBAWff-ffVt-QCQeyC2rXMbGa_psR6FgfpWFqZ5KeisZ2h2BlT0Gi2eQcKVtmqywZ7HpxFEPgo5zp-QjtUmEnAES',
    'AI Logistics Dashboard',
    'Biznexa didn''t just provide a tool; they transformed our entire digital architecture. Their approach has set a new benchmark for what''s possible.',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA39dAxR9YZVgFTIudq8UvVHpwyh4vL5FsGYdmOONfKAbAWFbmDBlgLQPZ0Ctl2q4Izf9z4uyzck6_whZbYOjBW2keOStaU9071r3jqs9K4Q8I2eO96_6iCudlne_fL6GWy282SLQ5RMxj8nKPx83DJi6cUHfL5Nkbbwj2BuNZDUD7IRSvmFIyFS_uZzYm4nHON2yAu0InYEpnmIm93vc8HnteJtx1qvAwHX7Ypf_pm_8KHvxyOEgwzQd_BIMPIYoB9JTofNsedXNwi',
    '["ecommerce-redesign","seo-market-dominance"]',
    1,
    1
  ),
  (
    'ecommerce-redesign',
    'E-Commerce Revenue Surge',
    'ArtisanCraft India',
    'Executive Sponsor',
    'Web Development',
    'A complete platform redesign that increased conversion rates by 280% and reduced cart abandonment.',
    'ArtisanCraft''s existing Shopify store had a 78% cart abandonment rate and page load times exceeding 8 seconds. Mobile users accounted for 70% of traffic but only 15% of conversions.',
    'We rebuilt the entire platform on a headless commerce architecture with Next.js, achieving sub-2-second load times. We redesigned the checkout flow to 3 steps and implemented AI-powered product recommendations.',
    '[{"metric":"280%","label":"Conversion Increase"},{"metric":"1.8s","label":"Page Load Time"},{"metric":"45%","label":"Cart Abandonment Drop"},{"metric":"INR 2.1Cr","label":"Q1 Revenue"}]',
    '["Next.js","Shopify Hydrogen","Tailwind CSS","Vercel"]',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDd3UUy35oCMyX66vZHBASNxgGruCgFnWgYB7EowfvSXV7fbbLTFAP678DYe_y1-XqcLHWPegF1tBxGddSYCtZcuudMZLg4OIyckICpLFxPd0y-bv-SY8GvCBU7qVTdhmntUu-0vLYjakflICcQxW9-ekzDZdwFaBBhD8TJl1QBWtXxX8hgSeDs8GftUi1V5xEJnM9H2JTmqFcZ4bH9J1V_nKcD1P1gBl8f-q0x0vjyYJNg46TWAPZDH9RLRwddQX7xQYB_u31QMiM9',
    'E-Commerce Platform',
    'Biznexa gave us a storefront that finally performed like our brand deserved. The speed gains alone changed the business.',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA39dAxR9YZVgFTIudq8UvVHpwyh4vL5FsGYdmOONfKAbAWFbmDBlgLQPZ0Ctl2q4Izf9z4uyzck6_whZbYOjBW2keOStaU9071r3jqs9K4Q8I2eO96_6iCudlne_fL6GWy282SLQ5RMxj8nKPx83DJi6cUHfL5Nkbbwj2BuNZDUD7IRSvmFIyFS_uZzYm4nHON2yAu0InYEpnmIm93vc8HnteJtx1qvAwHX7Ypf_pm_8KHvxyOEgwzQd_BIMPIYoB9JTofNsedXNwi',
    '["ai-logistics-transformation","seo-market-dominance"]',
    1,
    2
  ),
  (
    'seo-market-dominance',
    'From Page 5 to Page 1',
    'Zenith Legal Associates',
    'Executive Sponsor',
    'Digital Marketing',
    'A comprehensive SEO overhaul that took a law firm from obscurity to the top of Google search results.',
    'Zenith Legal had no online presence despite being a reputable firm for 15 years. Their website was a basic WordPress template with no SEO optimization, ranking on page 5+ for all target keywords.',
    'We executed a full technical SEO audit, rebuilt the site with proper schema markup, created a content strategy targeting 50+ keywords, and built a local SEO campaign with Google Business Profile optimization.',
    '[{"metric":"Page 1","label":"Google Ranking"},{"metric":"520%","label":"Organic Traffic"},{"metric":"34","label":"Keywords on Page 1"},{"metric":"3x","label":"Client Inquiries"}]',
    '["Next.js","Schema.org","Google Analytics","Ahrefs"]',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAbtiicdNvZKIqk7-GlgEwKXOmQkABVKPL5s7W3WdEiqKSzHxobNpRLDjYesfOoBC2eVXf_FDe2jFsRutn6D9fqHZDRiUtyhgls2vlhCe2qvDTeTKA4xwV3BAfZ-DxRpNpQzB3VDijqGOuWhIoSqm7pBYsG9hvkwLinjANcVo0v_bh2DWjLX1Yamiw0PQxzKYya_nicxATPVYkCHmJsVywMZ07FaiGdxc10er68DtuWy_H6oSIjbnytJB5x5lLqAv4zxXCFtQE13mtF',
    'SEO Analytics',
    'Their SEO system turned our website into a real acquisition channel. We went from invisible to a category leader.',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA39dAxR9YZVgFTIudq8UvVHpwyh4vL5FsGYdmOONfKAbAWFbmDBlgLQPZ0Ctl2q4Izf9z4uyzck6_whZbYOjBW2keOStaU9071r3jqs9K4Q8I2eO96_6iCudlne_fL6GWy282SLQ5RMxj8nKPx83DJi6cUHfL5Nkbbwj2BuNZDUD7IRSvmFIyFS_uZzYm4nHON2yAu0InYEpnmIm93vc8HnteJtx1qvAwHX7Ypf_pm_8KHvxyOEgwzQd_BIMPIYoB9JTofNsedXNwi',
    '["ai-logistics-transformation","ecommerce-redesign"]',
    1,
    3
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  client = VALUES(client),
  client_role = VALUES(client_role),
  category = VALUES(category),
  excerpt = VALUES(excerpt),
  challenge = VALUES(challenge),
  solution = VALUES(solution),
  results_json = VALUES(results_json),
  technologies_json = VALUES(technologies_json),
  cover_image = VALUES(cover_image),
  cover_image_alt = VALUES(cover_image_alt),
  client_quote = VALUES(client_quote),
  client_image = VALUES(client_image),
  related_slugs_json = VALUES(related_slugs_json),
  published = VALUES(published),
  sort_order = VALUES(sort_order);
